CREATE TABLE cadastro
(
  nome  VARCHAR(50) NOT NULL
 ,docto VARCHAR(20) NOT NULL
);

--INICIA A TRANSAÇAO
BEGIN TRANSACTION;

--INSERE REGISTROS
INSERT INTO cadastro VALUES ('Andre','1234565');
INSERT INTO cadastro VALUES ('Luiz', '1233211');
INSERT INTO cadastro VALUES ('Ana',  '1974562');

--SELECT DOS REGISTROS
SELECT * FROM cadastro;

--RETORNA A TABELA NO ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK

--EFETIVA AS INFORMAÇÕES NA TABELA 
COMMIT TRANSACTION;


--Ex 2 
--LIMPANDO A TABELA
DELETE FROM cadastro;

BEGIN TRANSACTION

--INSERINDO DADOS
INSERT INTO cadastro VALUES ('Luiz','123456')

--CRIANDO PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a1;

--INSERINDO DADOS
INSERT INTO cadastro VALUES ('Ana', '123');

--CRIANDO OUTRO PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a2;

--INSERINDO DADOS
INSERT INTO cadastro VALUES ('Antonio', '1234');

--CRIANDO OUTRO PONTO DE RECUPERAÇÃO
SAVE TRANSACTION a3;


--FAZENDO O ROLLBACK PARA UM PONTO ESPECIFICO
ROLLBACK TRANSACTION a2


--FAZENDO O ROLLBACK 
ROLLBACK;


--SALVANDO AS INFORMAÇÕES NA TABELA
COMMIT TRANSACTION;


--VERIFICANDO DADOS
SELECT * FROM cadastro