USE CURSO
--DECLARA AS VARIAVEIS QUE SERÃO UTILIZADAS
DECLARE @Nome_Aluno VARCHAR(100)
       ,@Id_Aluno   INT

--DECLARANDO O CURSOR
DECLARE meu_cursor
CURSOR LOCAL FOR SELECT id_aluno, nome FROM alunos

--ABRINDO O CURSOR
OPEN meu_cursor

--LENDO A PRÓXIMA LINHA
FETCH NEXT FROM meu_cursor INTO @Id_Aluno, @Nome_Aluno

--PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
WHILE(@@FETCH_STATUS = 0)
BEGIN
  PRINT CAST(@Id_Aluno AS VARCHAR(10)) + ' - ' + @Nome_Aluno + ' | FETCH_STATUS -> ' + CAST(@@FETCH_STATUS AS VARCHAR(10))

  -- CHAMANDO A PRÓXIMA LINHA
  FETCH NEXT FROM meu_cursor INTO @Id_Aluno, @Nome_Aluno
END

PRINT 'FETCH_STATUS -> ' + CAST(@@FETCH_STATUS AS VARCHAR(10));

-- FECHANDO CURSOR PARA LEITURA
CLOSE meu_cursor

-- FINALIZANDO O CURSOR
DEALLOCATE meu_cursor